name: Warframe精通进度【定时自动更新】
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    env:
      USER_ID: ${{ secrets.WF_USER_ID }}
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖 requests
        run: pip install requests

      - name: 运行数据抓取脚本
        run: python fetch.py

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
